// import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google';
import "./globals.css";

const inter = Inter({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata = {
  title: "Piket Bos?",
  description: "Generated by create next app",
  // themeColor: "#000000",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head> */}
      <body
        className={inter.className}
      >
        {children}
      </body>
    </html>
  );
}
